"""PlatformIO pre-build script.

Generates `src/generated/flame_lottie.h` from `assets/flame.lottie`.

Note: PlatformIO executes `extra_scripts` as SCons scripts (not as standalone
Python programs), so we use `Import("env")` to get `PROJECT_DIR`.
"""

import json
import os
import zipfile

Import("env")  # type: ignore


def _read_manifest(z: zipfile.ZipFile) -> dict:
    with z.open("manifest.json") as f:
        return json.loads(f.read().decode("utf-8"))


def _pick_animation_json_path(manifest: dict, zip_names: list[str]) -> str:
    # dotLottie manifests vary a bit by producer.
    # We prefer an explicit animation entry if present; otherwise, fall back to
    # the first .json file that's not the manifest.
    animations = manifest.get("animations")
    if isinstance(animations, list) and animations:
        first = animations[0]
        if isinstance(first, dict):
            for key in ("path", "file", "src"):
                p = first.get(key)
                if isinstance(p, str) and p in zip_names and p.lower().endswith(".json"):
                    return p

    json_candidates = [n for n in zip_names if n.lower().endswith(".json") and n != "manifest.json"]
    if not json_candidates:
        raise RuntimeError("No animation JSON found inside .lottie")
    # Stable pick.
    json_candidates.sort()
    return json_candidates[0]


def _emit_header(json_bytes: bytes, out_path: str) -> None:
    anim = json.loads(json_bytes.decode("utf-8"))
    markers = anim.get("markers")
    if not isinstance(markers, list):
        markers = []

    def _find_marker(name: str) -> tuple[bool, int, int]:
        for m in markers:
            if not isinstance(m, dict):
                continue
            cm = m.get("cm")
            if cm != name:
                continue
            tm = m.get("tm")
            dr = m.get("dr")
            if not isinstance(tm, (int, float)) or not isinstance(dr, (int, float)):
                return (False, 0, 0)
            start = int(round(tm))
            count = int(round(dr))
            if count < 0:
                count = 0
            return (True, start, count)
        return (False, 0, 0)

    has_flame, flame_start, flame_count = _find_marker("Flame Burn")
    has_load, load_start, load_count = _find_marker("Log Loading")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    # Emit as a byte array to avoid escaping issues.
    # The JSON is UTF-8; most tools produce ASCII-only, but we don't assume.
    cols = 24
    lines = []
    for i in range(0, len(json_bytes), cols):
        chunk = json_bytes[i : i + cols]
        lines.append(",".join(str(b) for b in chunk))
    arr = ",\n  ".join(lines)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gen_flame_lottie_header.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace assets {\n")
        f.write("static const std::uint8_t kFlameLottieJsonBytes[] = {\n  ")
        f.write(arr)
        f.write("\n};\n")
        f.write("static constexpr std::size_t kFlameLottieJsonSize = sizeof(kFlameLottieJsonBytes);\n")
        f.write("\n")
        f.write("// Marker segments extracted from the animation JSON.\n")
        f.write("// In Bodymovin/Lottie JSON, marker time (tm) and duration (dr) are in frame units.\n")
        f.write(f"static constexpr bool kHasMarkerFlameBurn = {str(has_flame).lower()};\n")
        f.write(f"static constexpr int kMarkerFlameBurnStartFrame = {flame_start};\n")
        f.write(f"static constexpr int kMarkerFlameBurnFrameCount = {flame_count};\n")
        f.write(f"static constexpr bool kHasMarkerLogLoading = {str(has_load).lower()};\n")
        f.write(f"static constexpr int kMarkerLogLoadingStartFrame = {load_start};\n")
        f.write(f"static constexpr int kMarkerLogLoadingFrameCount = {load_count};\n")
        f.write("}  // namespace assets\n")


def generate() -> None:
    project_dir = env["PROJECT_DIR"]
    lottie_path = os.path.join(project_dir, "assets", "flame.lottie")
    out_header = os.path.join(project_dir, "src", "generated", "flame_lottie.h")

    if not os.path.exists(lottie_path):
        raise RuntimeError(f"Missing {lottie_path}")

    with zipfile.ZipFile(lottie_path) as z:
        names = z.namelist()
        if "manifest.json" not in names:
            raise RuntimeError(".lottie missing manifest.json")
        manifest = _read_manifest(z)
        anim_path = _pick_animation_json_path(manifest, names)
        with z.open(anim_path) as f:
            json_bytes = f.read()

    _emit_header(json_bytes, out_header)
    print(
        "Generated %s from %s"
        % (os.path.relpath(out_header, project_dir), os.path.relpath(lottie_path, project_dir))
    )


# Run at SCons script import time.
generate()
